source 'http://rubygems.org'

gem 'rails', '3.2.3'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'bootstrap-sass', '~> 2.0.4.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'turbolinks', github: 'rails/turbolinks'
end

gem 'jquery-rails'

gem 'jquery-rails'
